### ISSUE TITLE
EPIC: make waltz great again

### ISSUE THREAD

**Issue by erdogan** [PataraLabs/api-docs#12]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] https://github.com/PataraLabs/api-docs/issues/9
- [ ] https://github.com/PataraLabs/api-docs/issues/8
- [ ] https://github.com/PataraLabs/api-docs/issues/7
```
